package com.example.demo.util;

import com.example.demo.payload.ErrorData;

import java.util.List;

public interface MessageConstants {
    String YOU_HAVE_NOT_PERMISSION = "YOU_HAVE_NOT_PERMISSION";
    String METHOD_ERROR = "METHOD_ERROR";
    String NO_ACCEPTABLE = "NO_ACCEPTABLE";
    String INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
    String FULL_AUTHENTICATION_REQUIRED = "FULL_AUTHENTICATION_REQUIRED";
    String MUST_NOT_BE_BLANK_EMAIL = "MUST_NOT_BE_BLANK_EMAIL";
    String MUST_NOT_BE_BLANK_PASSWORD = "MUST_NOT_BE_BLANK_PASSWORD";
    String USER_NOT_FOUND_OR_DISABLED = "USER_NOT_FOUND_OR_DISABLED";
    String LOGIN_OR_PASSWORD_ERROR = "LOGIN_OR_PASSWORD_ERROR";
    String SUCCESSFULLY_TOKEN_GENERATED = "SUCCESSFULLY_TOKEN_GENERATED";
    String TOKEN_INVALID = "TOKEN_INVALID";
    String USER_PERMISSION_RESTRICTION = "USER_PERMISSION_RESTRICTION";
    String REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED";
    String ORDER_NOT_FOUND = "ORDER_NOT_FOUND";
}

